@startuml
  node Magasin {
    component "Nginx" 
    component "store_manager.py" 
    database "MySQL 1"
    database "Redis"
    "NGINX" <--> "store_manager.py"
    "store_manager.py" <--> "MySQL 1"
    "store_manager.py" <--> "Redis"
  }

  node ServicePaiement {
    component "payment_service.py" 
    database "MySQL 2"
    "payment_service.py" <--> "MySQL 2"
  }

  "NGINX"  <-- "payment_service.py" : HTTPS
  "store_manager.py"  --> "payment_service.py" : HTTPS
@enduml